name: brunoai
description: Bruno AI - Your personal meal planning bear with shopping superpowers
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  
  # State Management
  provider: ^6.1.1
  
  # Networking & API
  http: ^1.1.0
  dio: ^5.4.0
  connectivity_plus: ^5.0.2
  
  # Local Storage
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # UI & Design
  google_fonts: ^6.1.0
  flutter_animate: ^4.3.0
  glassmorphism: ^3.0.0
  blur: ^3.1.0
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  lottie: ^2.7.0
  
  # Utils
  url_launcher: ^6.2.1
  intl: ^0.18.1
  uuid: ^4.2.1
  
  # Notifications
  flutter_local_notifications: ^17.2.3
  
  # Error Tracking & Analytics
  firebase_core: ^2.24.2
  firebase_crashlytics: ^3.4.9
  firebase_analytics: ^10.7.4
  
  # Security
  crypto: ^3.0.3
  
  # Platform-specific
  device_info_plus: ^9.1.1
  package_info_plus: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
  
  # fonts:
  #   - family: SFProDisplay
  #     fonts:
  #       - asset: assets/fonts/SFProDisplay-Regular.ttf
  #         weight: 400
  #       - asset: assets/fonts/SFProDisplay-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/SFProDisplay-Semibold.ttf
  #         weight: 600
  #       - asset: assets/fonts/SFProDisplay-Bold.ttf
  #         weight: 700